import hashlib
import random
import sys
import re

random.seed(44191)

lnames = [
    'Artois',
    'Ausloos',
    'Ausloos',
    'Bekaert',
    'Bogers',
    'Coremans',
    'De Bel',
    'De Clercq',
    'De Smet',
    'De Wyngaert',
    'Dekleermaeker',
    'Geurts',
    'Gevaert',
    'Hamelryck',
    'Happaerts',
    'Hotters',
    'Jacobs',
    'Kaja',
    'Kazantsev',
    'Langui',
    'Leysen',
    'Loddewijkx',
    'Massie',
    'Pasteels',
    'Saint',
    'Sateur',
    'Segal Stanciu',
    'Stalpaert',
    'Swennen',
    'Tashfeen',
    'Tollet',
    'Tyberghein',
    'Van Beersel',
    'Van Beneden',
    'Van den Bosch',
    'Van den Briel',
    'Van der Perre',
    'Van Hecke',
    'Van Kerkhoven',
    'Van Reeth',
    'Van Woensel',
    'Vanbriel',
    'Vandebroeck',
    'Vandenberghen',
    'Vander Hulst',
    'Vanophalvens',
    'Vanspauwen',
    'Verbaendert',
    'Verbeken',
    'Verheyden',
    'Verstraeten',
    'Willendyck',
    'Yermolovich',
    'Zegers',
    'Aerts',
    'Batista Barias',
    'Heylen',
    'Pauwels',
    'Van Esbroeck',
    'Verheyden',
]

fnames = [
    'Arne',
    'Frederik',
    'Lowie',
    'Eline',
    'Darius',
    'Sam',
    'Ruben',
    'Tibo',
    'Karel',
    'Nick',
    'Tim',
    'Tom',
    'Nathan',
    'Axel',
    'Tommi',
    'Kenzo',
    'Sibren',
    'Blenda',
    'Nikita',
    'Kim',
    'Andreas',
    'Gust',
    'Jens',
    'Koen',
    'Filip',
    'Maxime',
    'Andrei',
    'Connor',
    'Wout',
    'Asif',
    'Niels',
    'Ruben',
    'Hendrik',
    'Maarten',
    'Vincent',
    'Abel',
    'Tim',
    'Vito',
    'Wout',
    'Arno',
    'TijsEmiel',
    'Bram',
    'Timothy',
    'Jasper',
    'Jentse',
    'Wouter',
    'Arnaud',
    'Liwady',
    'Sander',
    'Jeroen',
    'Lars',
    'Andrej',
    'Jonas',
    'Bjorn',
    'Bert',
    'Hans',
    'Jordy',
    'Redginald',
]

def random_name():
    global fnames, lnames
    fname = random.choice(fnames)
    lname = random.choice(lnames)
    if not re.fullmatch(r'[a-zA-Z]+', fname) or not re.fullmatch(r'[a-zA-Z ]+', lname):
        print("Invalid name!")
        sys.exit(-1)
    return f'{fname} {lname}'

with open('input.txt', 'w') as out:
    out.write('\n'.join(random_name() for _ in range(500)))