import random

NQUESTIONS = 50
NSTUDENTS = 1000


rnd = random.Random(10348)

fnames = [
    "Adam",
    "Alexander",
    "Ali",
    "Angelo",
    "Anton",
    "Arnaud",
    "Aron",
    "Arthur",
    "Baljit",
    "Ben",
    "Boris",
    "Bram",
    "Brent",
    "Brick",
    "Bryan",
    "Cisse",
    "Dennis",
    "Dieter",
    "Elias",
    "Emilien",
    "Evert",
    "Firas",
    "Frederik",
    "Gillis",
    "Gregory",
    "Guillaume",
    "Hans",
    "Hendrik",
    "Igor",
    "Jakub",
    "Jasper",
    "Jelle",
    "Jens",
    "Jonas",
    "Joni",
    "Joran",
    "Jorian",
    "Jowan",
    "Jurgen",
    "Kasper",
    "Kjell",
    "Kobe",
    "Koen",
    "Kyanii",
    "Laurens",
    "Lennert",
    "Liam",
    "Liena",
    "Lorenzo",
    "Lucas",
    "Lukas",
    "Maarten",
    "Marlene",
    "Mathias",
    "Mathieu",
    "Matthias",
    "Mattias",
    "Maxim",
    "Merijn",
    "Michiel",
    "Mieke",
    "Milan",
    "Mirte",
    "Natan",
    "Nicky",
    "Nicolas",
    "Niels",
    "Niko",
    "Nona",
    "Obim",
    "Othello",
    "Phonkrit",
    "Pieterjan",
    "Preda",
    "Rafael",
    "Rainier",
    "Rick",
    "Rik",
    "Rishad",
    "Robbe",
    "Robin",
    "Roel",
    "Ruben",
    "Rubin",
    "Sam",
    "Sascha",
    "Sigfried",
    "Stanislas",
    "Stijn",
    "Szymon",
    "Sebastien",
    "Thao",
    "Thomas",
    "Timo",
    "Tom",
    "Tuan",
    "Ward",
    "Wout",
    "Wouter",
    "Xavier",
    "Yago",
    "Yang-Yee",
    "Yarne",
    "Yenthe",
    "Younes",
    "Yves"
]

lnames = [
  "Abdo",
  "Aert",
  "Ahmed",
  "Ausloos",
  "Ausloos",
  "Bastiaans",
  "Beddegenoodts",
  "Bijloos",
  "Bogers",
  "Bottu",
  "Braem",
  "Brouns",
  "Bruynseels",
  "Catalano",
  "Claes",
  "Clarysse",
  "Coget",
  "Coremans",
  "Dauwe",
  "De Baets",
  "De Clercq",
  "De Houwer",
  "De Ruysscher",
  "De Sutter",
  "Delarbre",
  "Demol",
  "Descendre",
  "Desmet",
  "Devos",
  "Dierckx",
  "Drabs",
  "Dubois",
  "Engels",
  "Freier",
  "Gataev",
  "Geerinckx",
  "Geldhof",
  "Gervais",
  "Gocmen",
  "Govaers",
  "Hamelryck",
  "Hendrickx",
  "Hendrix",
  "Hoek",
  "Hons",
  "Jacques",
  "Janssen",
  "Janssens",
  "Jeetun",
  "Jemuce",
  "Juste",
  "Kerckhofs",
  "Laporte",
  "Lemeire",
  "Lemmens",
  "Leurquin",
  "Liesenborgs",
  "Lowis",
  "Luypaert",
  "Madugba",
  "Man",
  "Meeus",
  "Melin",
  "Mergaerts",
  "Meyer",
  "Michiels",
  "Michils",
  "Morren",
  "Mounnadi",
  "Mustafa",
  "Nidecki",
  "Nowak",
  "Paeps",
  "Palmans",
  "Pasteels",
  "Paulus",
  "Pauwels",
  "Pechovitch",
  "Pesa",
  "Ramaekers",
  "Rizkallah",
  "Roden",
  "Roets",
  "Romeo",
  "Rubbens",
  "Rummens",
  "Rutten",
  "Scherens",
  "Sebrechts",
  "Seldeslachts",
  "Sels",
  "Sewnarain",
  "Singh",
  "Sol",
  "Spleesters",
  "Sterckx",
  "Symons",
  "Taverniers",
  "Temmerman",
  "Theunis",
  "Thiry",
  "Van Braeckel",
  "Van Briel",
  "Van de Velde",
  "Van den Cruijce",
  "Van der Zwalmen",
  "Van Eetvelt",
  "Van Gansen",
  "Van Grunderbeek",
  "Van Hoof",
  "Van Oosterwyck",
  "van Roekel",
  "Vanden Bosch",
  "Vanden Driesch",
  "Vandenplas",
  "Vanderborght",
  "Vanherf",
  "Vanheusden",
  "Vanluyten",
  "Vavedin",
  "Veelaert",
  "Venneman",
  "Vermeerbergen",
  "Verrycken",
  "Waem",
  "Wandzel",
  "Warlop",
  "Winderickx",
  "Wojtas"
]

def random_name():
    fname = rnd.choice(fnames)
    lname = rnd.choice(lnames)
    return f'{fname} {lname}'


solutions = [ rnd.choice('abcde') for _ in range(NQUESTIONS) ]

with open('solutions.csv', 'w') as file:
    print(",".join(solutions), file=file)


students = sorted(list(set( random_name() for _ in range(NSTUDENTS) )))

rnd.shuffle(students)

def random_answers():
    ability = rnd.randint(0, 100)
    def generate_answer(index):
        if rnd.randint(0, 100) < ability:
            return solutions[index]
        else:
            return rnd.choice('abcde')
    return [ generate_answer(i) for i in range(NQUESTIONS) ]

with open('answers.csv', 'w') as file:
    for student in students:
        answers = random_answers()
        line = ','.join([student] + answers)
        print(line, file=file)
